//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golf_3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bokningstid
    {
        public int id { get; set; }
        public Nullable<int> bokningsId { get; set; }
        public string huvudbokare { get; set; }
        public string person2 { get; set; }
        public string person3 { get; set; }
        public string person4 { get; set; }
    
        public virtual bokning bokning { get; set; }
    }
}
