//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golf_3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medbokare
    {
        public int Id { get; set; }
        public string Medbokare1 { get; set; }
        public int BokningsId { get; set; }
        public Nullable<bool> gast { get; set; }
        public Nullable<bool> incheckad { get; set; }
    }
}
