//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golf_3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resultat
    {
        public int Id { get; set; }
        public int resultat1 { get; set; }
        public string tavlande { get; set; }
        public int tavlingsId { get; set; }
        public string tavlingsnamn { get; set; }
    }
}
