//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golf_3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scorekort
    {
        public int Id { get; set; }
        public string Hole_nr { get; set; }
        public string Lenght_Tee1 { get; set; }
        public string Lenght_Tee2 { get; set; }
        public string Par { get; set; }
        public Nullable<int> Index { get; set; }
    }
}
