//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golf_3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slope
    {
        public int Id { get; set; }
        public string Tee { get; set; }
        public Nullable<decimal> Kvinna_CR { get; set; }
        public Nullable<decimal> Kvinna_Slope { get; set; }
        public Nullable<decimal> Herr_CR { get; set; }
        public Nullable<decimal> Herr_Slope { get; set; }
    }
}
