//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golf_3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tavling
    {
        public int Id { get; set; }
        public string tavlingsNamn { get; set; }
      
        public Nullable<System.DateTime> tavlingsDatum { get; set; }
      
        public Nullable<System.TimeSpan> forstaStarttid { get; set; }
        
        public Nullable<System.DateTime> sistaAnmalning { get; set; }
        public string tavlingsForm { get; set; }
        public Nullable<bool> publicerad { get; set; }
    }
}
